[programs]
image = "mpv"   # Set your preferred image viewer, like feh, sxiv, etc.
video = "mpv"   # Set your preferred video player, like mpv, vlc, etc.
[manager]
show_hidden = false 
ratio = [1, 3, 2]

